version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    networks:
      - data-pipeline-net

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - data-pipeline-net

  zookeeper:
    container_name: zookeeper-container
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - data-pipeline-net

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9094:9094"
      - "9095:9095"  # WSL 접속용 포트 추가
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,INTERNAL://kafka:29092,EXTERNAL://localhost:9094,EXTERNAL2://172.20.113.119:9095
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9094,EXTERNAL2://0.0.0.0:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,EXTERNAL2:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-container:2181
      KAFKA_CREATE_TOPICS: "test-topic:1:1,marketing.analysis.request:1:1"
    networks:
      - data-pipeline-net

networks:
  data-pipeline-net:
    driver: bridge

volumes:
  postgres-db-volume:
    driver: local

# docker-compose -f docker-compose-with-wsl.yml up -d